on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 🔨 Build Project
      run: |
        npm ci
        npx nx build

    - name: 📂 Sync files
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: true
        host: ${{ secrets.FTP_SERVER }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
        port: 22
        username: ${{ secrets.FTP_USERNAME }} # FTP username
        password: ${{ secrets.FTP_PASSWORD }} # FTP password
        remote_folder: ./subdomains/try-out/
        local_folder: dist
        cleanup: true
        include: []
        exclude: []
